# Handling Missing Data

In [1]:
import pandas as pd
import numpy as np

In [2]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [3]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [4]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])
string_data

0    aardvark
1         NaN
2        None
3     avocado
dtype: object

In [5]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

# Filtering Out Missing Data

In [9]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [10]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [11]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [12]:
data[~data.isna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [13]:
data = pd.DataFrame([[1, 6.5, 3], [1, np.nan, np.nan], 
                    [np.nan, np.nan, np.nan], [np.nan, 6.5, 3]])
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [14]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

In [15]:
data.dropna(how = "all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [18]:
data.dropna(axis = 1, how = "all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [19]:
df = pd.DataFrame(np.random.standard_normal((7, 3)))
df.iloc[:4, 1] = np.nan
df.iloc[:2, 2] = np.nan

In [20]:
df

0         1         2
0 -1.682085       NaN       NaN
1  0.783627       NaN       NaN
2 -1.496586       NaN  0.505207
3 -1.527555       NaN -0.993092
4  0.604827 -2.176623  0.660418
5 -0.051337  0.871058  0.720864
6  0.195705  0.450287 -0.134266

In [22]:
df.dropna(thresh=2, axis = 0)

0         1         2
2 -1.496586       NaN  0.505207
3 -1.527555       NaN -0.993092
4  0.604827 -2.176623  0.660418
5 -0.051337  0.871058  0.720864
6  0.195705  0.450287 -0.134266

In [31]:
df.dropna(thresh=2, axis = 1)

0         1         2
0 -1.682085       NaN       NaN
1  0.783627       NaN       NaN
2 -1.496586       NaN  0.505207
3 -1.527555       NaN -0.993092
4  0.604827 -2.176623  0.660418
5 -0.051337  0.871058  0.720864
6  0.195705  0.450287 -0.134266

In [32]:
df.dropna()

0         1         2
4  0.604827 -2.176623  0.660418
5 -0.051337  0.871058  0.720864
6  0.195705  0.450287 -0.134266

# Filling In Missing Data

In [34]:
df.fillna(value = 0)

0         1         2
0 -1.682085  0.000000  0.000000
1  0.783627  0.000000  0.000000
2 -1.496586  0.000000  0.505207
3 -1.527555  0.000000 -0.993092
4  0.604827 -2.176623  0.660418
5 -0.051337  0.871058  0.720864
6  0.195705  0.450287 -0.134266

In [36]:
# different columns filling different data
df.fillna({1:0.5, 2:0})

0         1         2
0 -1.682085  0.500000  0.000000
1  0.783627  0.500000  0.000000
2 -1.496586  0.500000  0.505207
3 -1.527555  0.500000 -0.993092
4  0.604827 -2.176623  0.660418
5 -0.051337  0.871058  0.720864
6  0.195705  0.450287 -0.134266

In [37]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))
df.iloc[2:, 1] = np.nan
df.iloc[4:, 2] = np.nan
df

0         1         2
0  0.557801 -0.315330  0.656849
1  0.514484 -0.876827  1.388300
2  1.268888       NaN -0.784812
3  0.000202       NaN  1.648947
4  0.272461       NaN       NaN
5  0.417390       NaN       NaN

In [39]:
df.ffill()

0         1         2
0  0.557801 -0.315330  0.656849
1  0.514484 -0.876827  1.388300
2  1.268888 -0.876827 -0.784812
3  0.000202 -0.876827  1.648947
4  0.272461 -0.876827  1.648947
5  0.417390 -0.876827  1.648947

In [41]:
df.ffill(limit=2)

0         1         2
0  0.557801 -0.315330  0.656849
1  0.514484 -0.876827  1.388300
2  1.268888 -0.876827 -0.784812
3  0.000202 -0.876827  1.648947
4  0.272461       NaN  1.648947
5  0.417390       NaN  1.648947

In [42]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [49]:
data.fillna(value = data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

# Data Transformation
### Removing Duplicates

In [6]:
data =  pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"], 
                     "k2": [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [7]:
data.duplicated()

In [52]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [9]:
data["v1"] = range(7)
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [11]:
data.drop_duplicates(subset=["k1"])

k1  k2  v1
0  one   1   0
1  two   1   1

In [12]:
data.drop_duplicates(subset=["k1", "k2"], keep = "last")

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

### Transforming Data Using a Function or Mapping

In [13]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon", 
                             "pastrami", "corned beef", "bacon", 
                             "pastrami", "honey ham", "nova lox"], 
                    "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [17]:
meat_to_animal = {"bacon": "pig", 
                 "pulled pork": "pig", 
                 "pastrami": "cow", 
                 "corned beef": "cow", 
                 "honey ham": "pig", 
                 "nova lox": "salmon"}
meat_to_animal

{'bacon': 'pig',
 'pulled pork': 'pig',
 'pastrami': 'cow',
 'corned beef': 'cow',
 'honey ham': 'pig',
 'nova lox': 'salmon'}

In [20]:
data["animal"] = data["food"].map(meat_to_animal)
# pd.Series.map(data["food"], meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [71]:
def get_animal(x):
    return meat_to_animal[x]

In [73]:
data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

# Replacing Values

In [74]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [75]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [77]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [78]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [79]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

# Renaming Axis Indexes

In [21]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)), 
                   index = ["Ohio", "Colorado", "New York"], 
                   columns = ["one", "two", "three", "four"])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [23]:
def transform(x):
    return x.upper()

data.index.map(transform)

Index(['OHIO', 'COLORADO', 'NEW YORK'], dtype='object')

In [24]:
data.index = data.index.map(transform)
data

one  two  three  four
OHIO        0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

In [29]:
data.rename(index = str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [32]:
data.rename(index = {"OHIO": "INDIANA"}, 
           columns = {"three": "peekaboo"})

one  two  peekaboo  four
INDIANA     0    1         2     3
COLORADO    4    5         6     7
NEW YORK    8    9        10    11

# Discretization and Bining

In [10]:
import pandas as pd
import numpy as np

ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]

age_categories = pd.cut(ages, bins)
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [11]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [12]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [13]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [15]:
pd.Series.value_counts(age_categories)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

# Detecting and Filtering Outliers

In [16]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.058214    -0.070190     0.028314    -0.001607
std       1.036630     1.044867     1.016691     0.998808
min      -3.192894    -3.506798    -3.007206    -3.804720
25%      -0.737827    -0.808450    -0.636871    -0.686821
50%      -0.036182    -0.097788     0.022640     0.002171
75%       0.625125     0.624190     0.704666     0.665136
max       3.947801     2.845122     3.097094     2.730342

In [22]:
data[(data.abs() > 3).any(axis = 1)]

0         1         2         3
85  -3.192894 -0.170324  1.275919  0.913054
92   0.661159  1.898768  3.097094 -0.579457
268  3.947801 -1.025149 -2.267255  0.705597
276  1.577051 -0.351825  3.003392 -1.158052
290 -1.188087 -0.492407 -3.007206 -1.082237
427  2.042827  0.784508 -0.004333 -3.804720
638  3.164120  0.788145  0.017516  0.031671
665 -1.618461  1.595869 -0.198865 -3.110288
666 -3.095240  1.124792 -0.445536  2.038870
738  1.433870 -3.506798  0.829275 -0.173242
827 -0.191781 -3.394815 -0.242792  0.227407
835  3.029229 -0.269046  0.931469 -1.308672

# Permutation and Random Sampling

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))
df

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [4]:
sampler = np.random.permutation(5)
sampler

array([0, 2, 1, 3, 4])

In [6]:
df.iloc[sampler]

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
1   7   8   9  10  11  12  13
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [7]:
df.take(sampler)

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
1   7   8   9  10  11  12  13
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [8]:
column_sampler = np.random.permutation(7)
column_sampler

array([5, 4, 1, 0, 6, 3, 2])

In [9]:
df.take(column_sampler, axis = 1)

5   4   1   0   6   3   2
0   5   4   1   0   6   3   2
1  12  11   8   7  13  10   9
2  19  18  15  14  20  17  16
3  26  25  22  21  27  24  23
4  33  32  29  28  34  31  30

In [10]:
df.sample(n = 3)

0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20

In [11]:
choice = pd.Series([5, 7, -1, 6, 4])
choice.sample(n = 10, replace=True)

4    4
4    4
3    6
0    5
1    7
0    5
0    5
4    4
1    7
4    4
dtype: int64

In [14]:
df.sample(n = 10, replace=True, axis = 0)

0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20
1   7   8   9  10  11  12  13
3  21  22  23  24  25  26  27
0   0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
1   7   8   9  10  11  12  13

# Computing Indicator/Dummy Variables

In [16]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"], 
                  "data1": range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [19]:
pd.get_dummies(df["key"])

a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [20]:
dummies = pd.get_dummies(pd.get_dummies(df["key"], prefix = "key"))
df_with_dummy = df[["data1"]].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0  False   True  False
1      1  False   True  False
2      2   True  False  False
3      3  False  False   True
4      4   True  False  False
5      5  False   True  False

In [25]:
df[["data1"]]

data1
0      0
1      1
2      2
3      3
4      4
5      5

In [26]:
mnames = ["movie_id", "title", "genres"]
movies = pd.read_table("../../github/pydata-book/datasets/movielens/movies.dat", 
                      sep = "::", 
                      header=None, 
                      names=mnames, 
                      engine="python")
movies

movie_id                               title  \
0            1                    Toy Story (1995)   
1            2                      Jumanji (1995)   
2            3             Grumpier Old Men (1995)   
3            4            Waiting to Exhale (1995)   
4            5  Father of the Bride Part II (1995)   
...        ...                                 ...   
3878      3948             Meet the Parents (2000)   
3879      3949          Requiem for a Dream (2000)   
3880      3950                    Tigerland (2000)   
3881      3951             Two Family House (2000)   
3882      3952               Contender, The (2000)   

                            genres  
0      Animation|Children's|Comedy  
1     Adventure|Children's|Fantasy  
2                   Comedy|Romance  
3                     Comedy|Drama  
4                           Comedy  
...                            ...  
3878                        Comedy  
3879                         Drama  
3880                         Drama  
3881                         Drama  
3882                Drama|Thriller  

[3883 rows x 3 columns]

In [27]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [31]:
dummies = movies["genres"].str.get_dummies(sep = "|")
dummies

Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
0          0          0          1           1       1      0            0   
1          0          1          0           1       0      0            0   
2          0          0          0           0       1      0            0   
3          0          0          0           0       1      0            0   
4          0          0          0           0       1      0            0   
...      ...        ...        ...         ...     ...    ...          ...   
3878       0          0          0           0       1      0            0   
3879       0          0          0           0       0      0            0   
3880       0          0          0           0       0      0            0   
3881       0          0          0           0       0      0            0   
3882       0          0          0           0       0      0            0   

      Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  \
0         0        0          0       0        0        0        0       0   
1         0        1          0       0        0        0        0       0   
2         0        0          0       0        0        0        1       0   
3         1        0          0       0        0        0        0       0   
4         0        0          0       0        0        0        0       0   
...     ...      ...        ...     ...      ...      ...      ...     ...   
3878      0        0          0       0        0        0        0       0   
3879      1        0          0       0        0        0        0       0   
3880      1        0          0       0        0        0        0       0   
3881      1        0          0       0        0        0        0       0   
3882      1        0          0       0        0        0        0       0   

      Thriller  War  Western  
0            0    0        0  
1            0    0        0  
2            0    0        0  
3            0    0        0  
4            0    0        0  
...        ...  ...      ...  
3878         0    0        0  
3879         0    0        0  
3880         0    0        0  
3881         0    0        0  
3882         1    0        0  

[3883 rows x 18 columns]

In [33]:
movies_windic = movies.join(dummies.add_prefix("Genre_"))
movies_windic

movie_id                               title  \
0            1                    Toy Story (1995)   
1            2                      Jumanji (1995)   
2            3             Grumpier Old Men (1995)   
3            4            Waiting to Exhale (1995)   
4            5  Father of the Bride Part II (1995)   
...        ...                                 ...   
3878      3948             Meet the Parents (2000)   
3879      3949          Requiem for a Dream (2000)   
3880      3950                    Tigerland (2000)   
3881      3951             Two Family House (2000)   
3882      3952               Contender, The (2000)   

                            genres  Genre_Action  Genre_Adventure  \
0      Animation|Children's|Comedy             0                0   
1     Adventure|Children's|Fantasy             0                1   
2                   Comedy|Romance             0                0   
3                     Comedy|Drama             0                0   
4                           Comedy             0                0   
...                            ...           ...              ...   
3878                        Comedy             0                0   
3879                         Drama             0                0   
3880                         Drama             0                0   
3881                         Drama             0                0   
3882                Drama|Thriller             0                0   

      Genre_Animation  Genre_Children's  Genre_Comedy  Genre_Crime  \
0                   1                 1             1            0   
1                   0                 1             0            0   
2                   0                 0             1            0   
3                   0                 0             1            0   
4                   0                 0             1            0   
...               ...               ...           ...          ...   
3878                0                 0             1            0   
3879                0                 0             0            0   
3880                0                 0             0            0   
3881                0                 0             0            0   
3882                0                 0             0            0   

      Genre_Documentary  ...  Genre_Fantasy  Genre_Film-Noir  Genre_Horror  \
0                     0  ...              0                0             0   
1                     0  ...              1                0             0   
2                     0  ...              0                0             0   
3                     0  ...              0                0             0   
4                     0  ...              0                0             0   
...                 ...  ...            ...              ...           ...   
3878                  0  ...              0                0             0   
3879                  0  ...              0                0             0   
3880                  0  ...              0                0             0   
3881                  0  ...              0                0             0   
3882                  0  ...              0                0             0   

      Genre_Musical  Genre_Mystery  Genre_Romance  Genre_Sci-Fi  \
0                 0              0              0             0   
1                 0              0              0             0   
2                 0              0              1             0   
3                 0              0              0             0   
4                 0              0              0             0   
...             ...            ...            ...           ...   
3878              0              0              0             0   
3879              0              0              0             0   
3880              0              0              0             0   
3881              0              0              0             0   
3882         

In [39]:
np.random.seed(12345)
values = np.random.uniform(size = 10)
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [40]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0       False       False       False       False        True
1       False        True       False       False       False
2        True       False       False       False       False
3       False        True       False       False       False
4       False       False        True       False       False
5       False       False        True       False       False
6       False       False       False       False        True
7       False       False       False        True       False
8       False       False       False        True       False
9       False       False       False        True       False

# Extension Data Types

In [42]:
s = pd.Series([1, 2, 3, None])
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [44]:
s = pd.Series([1, 2, 3, None], dtype = pd.Int64Dtype())
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [45]:
s.isna()

0    False
1    False
2    False
3     True
dtype: bool

In [46]:
s.dtype

Int64Dtype()

In [48]:
s = pd.Series([1, 2, 3, None], dtype = "Int64")
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [1]:
import pandas as pd
import numpy as np

In [2]:
s = pd.Series(["one", "two", None, "three"], dtype = pd.StringDtype())
s

0      one
1      two
2     <NA>
3    three
dtype: string

In [3]:
df = pd.DataFrame({"A": [1, 2, None, 4], 
                  "B": ["one", "two", "three", None], 
                  "C": [False, None, False, True]})
df

A      B      C
0  1.0    one  False
1  2.0    two   None
2  NaN  three  False
3  4.0   None   True

In [5]:
df["A"] = df["A"].astype("Int64")
df["B"] = df["B"].astype("string")
df["C"] = df["C"].astype("boolean")
df

A      B      C
0     1    one  False
1     2    two   <NA>
2  <NA>  three  False
3     4   <NA>   True

# String Manipulation
### Python Built-In String Object Methods

In [13]:
val = "a,b,  guido"
val.split(sep = ",")

['a', 'b', '  guido']

In [17]:
pieces = [x.strip() for x in val.split(",")]
pieces

['a', 'b', 'guido']

In [14]:
first, second, thrid = pieces
first + "::" + second + "::" + thrid

'a::b::guido'

In [15]:
"::".join(pieces)

'a::b::guido'

# Regular Expressions

The `re` module functions fall into three categories: 
1. pattern matching
2. substitution
3. splitting

In [19]:
import re
text = "foo    bar\t baz  \tqux"

re.split(r"\s+", text)

['foo', 'bar', 'baz', 'qux']

In [20]:
regex = re.compile(r"\s+")
regex

re.compile(r'\s+', re.UNICODE)

In [21]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [22]:
regex.findall(text)

['    ', '\t ', '  \t']

In [25]:
text = """
Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan rya@yahoo.com
"""

pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

In [26]:
regex = re.compile(pattern=pattern, flags=re.IGNORECASE)

In [27]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'rya@yahoo.com']

In [28]:
m = regex.search(text)
m

<re.Match object; span=(6, 21), match='dave@google.com'>

In [29]:
text[m.start():m.end()]

'dave@google.com'

In [32]:
# match only if the pattern occures at the start of the string
print(regex.match(text))

None


In [33]:
print(regex.sub("REDACTED", text))


Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED



In [34]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"
regex = re.compile(pattern=pattern, flags=re.IGNORECASE)

m = regex.match("wesm@bridge.net")
m.groups()

('wesm', 'bridge', 'net')

In [35]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('rya', 'yahoo', 'com')]

In [36]:
print(regex.sub(r"Username: \1, Domain: \2, Suffix: \3", text))


Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: rya, Domain: yahoo, Suffix: com



# String Functions in pandas

In [5]:
data = {"Dave": "dave@google.com", 
        "Steve": "steve@gmail.com",
       "Rob": "rob@gmail.com", 
       "Wes": np.nan}
data = pd.Series(data, dtype = "string")
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string

In [6]:
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [7]:
data.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

In [9]:
import re

pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"
data.str.findall(pattern, flags = re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                       <NA>
dtype: object

In [12]:
matches = data.str.findall(pattern, flags = re.IGNORECASE).str[0]
matches

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                     <NA>
dtype: object

In [19]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes        <NA>
dtype: object

In [15]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes       <NA>
dtype: string

In [16]:
data.str.extract(pattern, flags = re.IGNORECASE)

0       1     2
Dave    dave  google   com
Steve  steve   gmail   com
Rob      rob   gmail   com
Wes     <NA>    <NA>  <NA>

# Categorical Data

In [20]:
values = pd.Series(["apple", "orange", "apple", "apple"] * 2)
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [21]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [23]:
pd.Series.value_counts(values)

apple     6
orange    2
Name: count, dtype: int64

In [24]:
values = pd.Series([0, 1, 0, 0] * 2)
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [25]:
dim = pd.Series(["apple", "orange"])
dim

0     apple
1    orange
dtype: object

In [26]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

# Categorical Extension Type in pandas

In [27]:
fruits = ["apple", "orange", "apple", "apple"] * 2
fruits

['apple', 'orange', 'apple', 'apple', 'apple', 'orange', 'apple', 'apple']

In [28]:
N = len(fruits)
N

8

In [31]:
rng = np.random.default_rng(seed = 12345)
df = pd.DataFrame({"fruit": fruits, 
                  "basket_id": np.arange(N), 
                  "count": rng.integers(3, 15, size = N)}, 
                  columns = ["basket_id", "fruit", "weight"])
df

basket_id   fruit weight
0          0   apple    NaN
1          1  orange    NaN
2          2   apple    NaN
3          3   apple    NaN
4          4   apple    NaN
5          5  orange    NaN
6          6   apple    NaN
7          7   apple    NaN

In [32]:
fruit_cat = df["fruit"].astype("category")
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [33]:
fruit_cat.array

['apple', 'orange', 'apple', 'apple', 'apple', 'orange', 'apple', 'apple']
Categories (2, object): ['apple', 'orange']

In [36]:
fruit_cat.array.categories

Index(['apple', 'orange'], dtype='object')

In [38]:
fruit_cat.array.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [39]:
dict(enumerate(fruit_cat))

{0: 'apple',
 1: 'orange',
 2: 'apple',
 3: 'apple',
 4: 'apple',
 5: 'orange',
 6: 'apple',
 7: 'apple'}

In [42]:
df["fruit"] = df["fruit"].astype("category")
df["fruit"]

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [43]:
my_categories = pd.Categorical(["foo", "bar", "baz", "foo", "bar"])
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [45]:
categories = ["foo", "bar", "baz"]
codes = [0, 1, 2, 0, 0, 1]
my_cat2 = pd.Categorical.from_codes(codes, categories, ordered = True)
my_cat2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

# Computations with Categoricals

In [46]:
rng = np.random.default_rng(seed = 12345)
draws = rng.standard_normal(1000)
draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [51]:
bins = pd.qcut(draws, 4)
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] < (0.687, 3.211]]

In [52]:
bins = pd.qcut(draws, 4, labels = ["Q1", "Q2", "Q3", "Q4"])
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [54]:
bins.codes[:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [59]:
bins = pd.Series(bins, name = "quartile")
bins

0      Q1
1      Q4
2      Q1
3      Q2
4      Q2
       ..
995    Q3
996    Q3
997    Q2
998    Q3
999    Q2
Name: quartile, Length: 1000, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [60]:
results = (pd.Series(draws)
          .groupby(bins)
          .agg(["count", "min", "max"])
          .reset_index())
results

/tmp/ipykernel_156/818495537.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby(bins)


quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

In [64]:
results["quartile"]

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [67]:
N = 1_000_000
labels = pd.Series(["foo", "bar", "baz", "qux"] * (N//4))
categories = labels.astype("category")

labels.memory_usage(deep = True)

60000128

In [68]:
categories.memory_usage(deep = True)

1000540

In [69]:
%timeit _ = labels.astype("category")

24.8 ms ± 192 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [70]:
%timeit labels.value_counts()

20.6 ms ± 867 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [71]:
%timeit categories.value_counts()

2.2 ms ± 57.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# Categorical Methods

In [90]:
s = pd.Series(["a", "b", "c", "d"] * 2)
cat_s = s.astype("category")
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [91]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [93]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')